# SECUENCIAS DE ESCAPE
# 1- # NUMERAL PARA COMENTAR TEXTO
# 2- \"" PARA DETALLAR COMILLAS DENTRO DEL STRING (COMO EN EJMPLO VARIABLE CURSO)
# 3- \ COMILLAS SIMPLES
# 4- \\ PARA DETALLAR
# 5- \n SALTO DE LINEA

curso = "Ultimate \"Python\""
print(curso)
